# Generated by Django 5.0.2 on 2025-05-27 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('game_name', models.CharField(max_length=200)),
                ('max_ltv_ratio', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('base_yield_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaucetClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NFTVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('estimated_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('utility_score', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('DEPOSITED', 'Deposited'), ('COLLATERALIZED', 'Used as Collateral'), ('PARTIAL_LIQUIDATED', 'Partially Liquidated'), ('LIQUIDATED', 'Fully Liquidated'), ('WITHDRAWN', 'Withdrawn')], default='DEPOSITED', max_length=20)),
                ('deposit_date', models.DateTimeField(auto_now_add=True)),
                ('last_yield_date', models.DateTimeField(blank=True, null=True)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaical_platform.nftcollection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('collection', 'token_id')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('current_debt', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ltv_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REPAID', 'Fully Repaid'), ('LIQUIDATED', 'Liquidated'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interest_update', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nft_collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaical_platform.nftvault')),
            ],
        ),
        migrations.CreateModel(
            name='DPOToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaical_platform.nftvault')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT_NFT', 'NFT Deposit'), ('WITHDRAW_NFT', 'NFT Withdrawal'), ('LOAN_CREATE', 'Loan Created'), ('LOAN_REPAY', 'Loan Repayment'), ('YIELD_RECEIVED', 'Yield Received'), ('PARTIAL_LIQUIDATION', 'Partial Liquidation'), ('FULL_LIQUIDATION', 'Full Liquidation'), ('FAUCET_CLAIM', 'Faucet Claim'), ('DPO_PURCHASE', 'DPO Token Purchase')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosaical_platform.loan')),
                ('related_nft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosaical_platform.nftvault')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vbtc_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YieldRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('yield_date', models.DateTimeField(auto_now_add=True)),
                ('applied_to_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosaical_platform.loan')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaical_platform.nftvault')),
            ],
        ),
    ]
