# Generated by Django 5.0.2 on 2025-05-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaical_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpotoken',
            name='current_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='dpotoken',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dpotoken',
            name='original_nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpo_tokens', to='mosaical_platform.nftvault'),
        ),
    ]
