# Generated by Django 5.0.2 on 2025-05-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaical_platform', '0002_dpotoken_current_price_dpotoken_is_for_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT_NFT', 'NFT Deposit'), ('WITHDRAW_NFT', 'NFT Withdrawal'), ('LOAN_CREATE', 'Loan Created'), ('LOAN_REPAY', 'Loan Repayment'), ('YIELD_RECEIVED', 'Yield Received'), ('PARTIAL_LIQUIDATION', 'Partial Liquidation'), ('FULL_LIQUIDATION', 'Full Liquidation'), ('FAUCET_CLAIM', 'Faucet Claim'), ('DPO_PURCHASE', 'DPO Token Purchase'), ('DPO_SALE', 'DPO Token Sale'), ('DPO_CREATED', 'DPO Token Created'), ('SWAP_COLLATERAL', 'Collateral Swap')], max_length=20),
        ),
    ]
