# Generated by Django 5.2.1 on 2025-05-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaical_platform', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('RESPONSE_TIME', 'Response Time'), ('DATABASE_QUERY', 'Database Query Time'), ('CACHE_HIT_RATE', 'Cache Hit Rate'), ('TRANSACTION_VOLUME', 'Transaction Volume'), ('USER_ACTIVITY', 'User Activity')], max_length=20)),
                ('value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('user_count', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='mosaical_pl_metric__2b6170_idx'), models.Index(fields=['endpoint', 'timestamp'], name='mosaical_pl_endpoin_3d7073_idx')],
            },
        ),
    ]
