# Generated by Django 5.2.1 on 2025-06-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosaical_platform', '0005_currency_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_currency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vnst_balance',
        ),
    ]
